config/routes.rb
Rails.application.routes.draw do
# mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
# authenticate :user, -> (u) { u.admin? } do # Supposing there is a User#admin? method
# mount ActiveAnalytics::Engine, at: "analytics" # http://localhost:3000/analytics
# end
  
  get 'profiles/index'
  resources :likes, only: [:create, :destroy]
  resources :comments

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :users, only: [:show]
  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"
  
  get 'homes/about'
  get 'posts/myposts'
  get 'posts/discover'
  resources :posts
  root "posts#index"
  
  get 'myposts', to: 'posts#myposts'
 
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_punchable
  
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true, length: { minimum: 5, maximum: 500 }
  validates :keywords, presence: true, length: { minimum: 5, maximum: 100 }
  
  # Associations
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many_attached :images
  has_many :comments
  has_many :likes

  before_create :randomize_id

  private

  def randomize_id
    begin
      self.id = SecureRandom.random_number(1_000_000_000)
    end while Post.where(id: self.id).exists?
  end
  
  def delete_related_data
    comments.destroy_all
    likes.destroy_all
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: [:index, :show]
  include Pagy::Backend
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc)
    #@tags = Tag.all
  end

  def discover
    @posts = Post.all
    @tags = Tag.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = @post.comments.build
    @tags = @post.tags
  end

  def myposts
    @posts = Post.all
    @tags = Tag.all
  end

  # GET /posts/new
  def new
    @post = Post.new
    
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    # 画像が存在する場合のみVisionを呼び出す
    # ["", "XXXX", "YYYY"]　=> ["XXXX", "YYYY"]
    # images = post_params[:images].??????
    # images.first
    #if post_params[:images].present? && post_params[:images].last.present?
      #tags = Vision.get_image_data(post_params[:images].last)
    #end
    
    # 画像が存在する場合のみVisionを呼び出す
  images = post_params[:images].reject(&:blank?)
  tags = []

  if images.present?
    tags = Vision.get_image_data(images.last).take(3) # 最大3つのタグを取得
  end

    respond_to do |format|
      if @post.save
        tags.each do |tag_name|
          # 既存のタグを探すか、新しいタグを作成する
          tag = Tag.find_or_create_by(name: tag_name)
          # PostTag を使用して、投稿とタグの間の関係を作成する
          @post.post_tags.create(tag: tag)
        end if tags

        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # DELETE /posts/1 or /posts/1.json
  def destroy
  @post.comments.destroy_all
  @post.likes.destroy_all
  @post.destroy

  respond_to do |format|
    format.html { redirect_to myposts_url, notice: "Post was successfully destroyed." }
    format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :description, :keywords, :user_id, images: [])
  end
  
  def record_not_found
    redirect_to posts_url, alert: "指定された投稿が見つかりませんでした。"
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
  include Pagy::Frontend
end

app/views/posts/_form.html.erb
<div class="col-xl-4 col-md-6 col-sm-8 col-10" style="margin: auto; background-color: #f8f8f8; border-radius: 6px; padding: 15px; box-shadow: 0px 0px 2px 2px (255, 255, 255, 0.1)">
  <%= form_with(model: post) do |form| %>
    <h1>New post</h1>
    <div>
      <% invalid = post.errors.include?(:title)%>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: "form-control" %>
      <% if invalid %>
        <p style="color:red">
          <%= post.errors.full_messages_for(:title).join(" ,")%>
        </p>
      <% end %>
    </div>
    <div>
      <%= form.text_field :user_id, type: "hidden", value: current_user.id %>
    </div>
    <div>
      <% invalid = post.errors.include?(:description)%>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description, class: "form-control" %>
      <% if invalid %>
        <p style="color:red">
          <%= post.errors.full_messages_for(:description).join(" ,")%>
        </p>
      <% end %>
    </div>
    <div>
      <% invalid = post.errors.include?(:keywords)%>
      <%= form.label :keywords, style: "display: block" %>
      <%= form.text_field :keywords, class: "form-control" %>
      <% if invalid %>
        <p style="color:red">
          <%= post.errors.full_messages_for(:keywords).join(" ,")%>
        </p>
      <% end %>
      <%= form.file_field :images, multiple:true %>
    </div>
    <div>
      <%= form.submit class:"btn btn-primary col-12" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="text-center post-container col-6" style="margin: auto;">
  <p>
    <%#= post.description %>
  </p>
  <p>
    <%#= link_to "", post, class:"post-link", style:"z-index:" %>
  </p>
  <% if user_signed_in? %>
    <% like = current_user.likes.find_by(post: post) %>
    <% if like.nil? %>
      <%= button_to "like", likes_path, params: { like: { post_id: post.id }}, method: :post%>
    <% else %>
      <%= button_to "Unlike", like_path(like), method: :delete %>
    <% end %>
  <% end %>
  <p> <%= post.likes.count %> Likes </p>
  <% post.images.each do |image| %>
    <%= image_tag(image, style: "
      max-width: 50%;
  height: auto; object-fit: contain;") %>
  <% end %>
  <p>
    <%= post.title %>
  </p>
</div>

<% @post.tags.each do |tag| %>
  <span class="tag"><%= tag.name %></span>
<% end %>

app/views/posts/discover.html.erb
<%= stylesheet_link_tag("post") %>
<p style="color: green"><%= notice %></p>
<div id="posts" class="text-center masonry-grid">
  <% @posts.each do |post| %>
    <div class="post-content masonry-item">
      <!-- 画像表示 -->
      <div class="post-image">
        <%= link_to post_path(post) do %>
          <%= image_tag post.images.first if post.images.any? %>
        <% end %>

        <div class="post-author">
          <%= link_to post.user.username, user_path(post.user) %>
        </div>

        <div class="like-button">
          <%= button_to "☆", like_path(post) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag("post") %>
<p style="color: green"><%= notice %></p>
<div id="posts" class="text-center masonry-grid">
  <% @posts.each do |post| %>
    <div class="post-content masonry-item">
      <!-- 画像表示 -->
      <div class="post-image">
        <%= link_to post_path(post) do %>
          <%= image_tag post.images.first if post.images.any? %>
        <% end %>

        <div class="post-author">
          <%= link_to post.user.username, user_path(post.user) %>
        </div>

        <div class="like-button">
          <%= button_to "☆", like_path(post) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.turbo_stream.erb
<%= turbo_stream.append :posts do %>
  <% @posts.each do |post| %>
    <% if user_signed_in? %>
      <% if current_user.following?(post.user) %>
        <%= render post %>
      <% end %>
    <% end %>
  <% end %>
  <% if !user_signed_in? %>
    <% @posts.each do |post| %>
      <%= render post%>
    <% end %>
  <% end %>
<% if @pagy && @pagy.next.present? %>
  <%= turbo_stream.replace :pagination do %>
    <%= turbo_frame_tag :pagination, loading: :lazy, src: posts_path(format: :turbo_stream, page: @pagy.next) %>
  <% end %>
<% end %>
<% end %>

app/views/posts/myposts.html.erb
<%= stylesheet_link_tag("post")%>
<p style="color: green"><%= notice %></p>
<div id="posts" class="text-center masonry-grid">
  <% @posts.each do |post| %>
    <% if post.user.id == current_user.id %>
      <div class="post-content masonry-item">
        <!-- 画像表示 -->
        <div class="post-image">
          <%= link_to post_path(post) do %>
            <%= image_tag post.images.first if post.images.any? %>
          <% end %>

          <div class="post-author">
            <%= link_to post.user.username, user_path(post.user) %>
          </div>

          <div class="like-button">
            <%= button_to "☆", like_path(post) %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row"><%= render "form", post: @post %>
</div>
<br>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @post %>
<%= link_to "Back to posts", posts_path %>
<% if user_signed_in? %>
  <% if current_user.id == @post.user.id %>
    <div>
      <%= link_to "Edit this post", edit_post_path(@post) %> |
      <%= button_to "Destroy this post", @post, method: :delete %>
    </div>
  <% end %>
<% end %>
<%= render "comments/form", comment: @comment %>
<%- @post.comments.each do |comment| %>
  <%= comment.text %>
  <br>
<% end %>


<ul>
  <% @tags.take(3).each do |tag| %>
    <li><%= tag.name %></li>
  <% end %>
</ul>

app/views/posts/users.html.erb
  <div id="posts" class="text-center">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</div>