config/routes.rb
Rails.application.routes.draw do
# mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
# authenticate :user, -> (u) { u.admin? } do # Supposing there is a User#admin? method
# mount ActiveAnalytics::Engine, at: "analytics" # http://localhost:3000/analytics
# end
  
  get 'profiles/index'
  resources :likes, only: [:create, :destroy]
  resources :comments

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :users, only: [:show]
  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"
  
  get 'homes/about'
  get 'posts/myposts'
  get 'posts/discover'
  resources :posts
  root "posts#index"
  
  get 'myposts', to: 'posts#myposts'
 
end

app/views/layouts/_footer.html.erb
<!-- app/views/shared/_footer.html.erb -->
<!-- Footer -->
<footer class="page-footer font-small blue pt-4">
  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">
    <!-- Grid row -->
    <div class="row">
      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">
        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>
      </div>
      <!-- Grid column -->
      <hr class="clearfix w-100 d-md-none pb-3">
      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">
        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>
        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>
      </div>
      <!-- Grid column -->
      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">
        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>
        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>
      </div>
      <!-- Grid column -->
    </div>
    <!-- Grid row -->
  </div>
  <!-- Footer Links -->
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2023 Copyright:
    <a href="/"> DigiFashionPortal.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag("navbar.css") %>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path do %>
    <%= image_tag("digifashionportal_logo_full.png", alt: "Home", class: "logo-image") %>
  <% end %>

  <div class="search-container d-flex align-items-center ml-auto">
    <%= form_with url: profiles_index_path, method: :get do |form| %>
      <%= form.search_field :query, value: params[:query], placeholder: "Search", class: "search-field flex-grow-1" %>
      <%= form.submit "Search", class: "btn btn-primary ml-2" %>
    <% end %>
  </div>
  
  <% if user_signed_in? %>
    <% if current_user.avatar.attached? %>
      <%= image_tag current_user.avatar, style:"width: 50px; height: 50px;" %>
    <% end %>
  <% end %>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active"></li>
      
      <li class="nav-item">
        <%= link_to "Upload Post", new_post_path, class: "nav-link" %>
      </li>
      
      <li class="nav-item">
        <%= link_to "About Page", homes_about_path, class:"nav-link"%>
      </li>
      
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to "Admin Panel", rails_admin_path, class:"nav-link"%>
          </li>
        <% end %>
        
        <li class="nav-item">
          <%= link_to "View my profile", current_user, class:"nav-link"%>
        </li>
        
        <li class="nav-item">
          <%= link_to "Discover Posts", posts_discover_path, class:"nav-link"%>
        </li>
        
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path,class:"nav-link", style:"border:none;"%>
        </li>
        
        <li class="nav-item">
          <%= link_to "Edit Account", edit_user_registration_path,class:"nav-link"%>
        </li>
        
        <li class="nav-item">
          <%= link_to "View my Posts", posts_myposts_path,class:"nav-link"%>
        </li>
      <% else %>
      
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class:"sign-up nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>DigiFashionPortal</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-cYrOq8hM16ir6bYG4pBlJEXU3QuQj2edM/fRSn8GntAsZQHzMgO6NSeF7Sz4bR5o9P1y1zyi+H5pd5cHl/F7zA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- Font Awesome Kit -->
    <script src="https://kit.fontawesome.com/2c22541028.js" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <!-- タブ上ファビコン -->
    <%= favicon_link_tag('favicon.ico') %>
  </head>
  
  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render "layouts/footer" %>

    <!-- Bootstrap JavaScript (with Popper.js) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY0iD75Fh7Ef+nz1zI0lWAg5CgABbPzQFAF8wE" crossorigin="anonymous"></script>
  </body>
</html>